# Generated by Django 6.1.1 on 2026-09-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government_schemes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentscheme',
            name='application_process_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='application_process_mr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='benefits_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='benefits_mr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='documents_required_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='documents_required_mr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='eligibility_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='eligibility_mr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='full_description_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='full_description_mr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='short_description_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='short_description_mr',
            field=models.TextField(blank=True),
        ),
    ]
