# Generated by Django 6.1.1 on 2026-09-07 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('government_schemes', '0002_governmentscheme_application_process_hi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governmentscheme',
            name='application_process_hi',
        ),
        migrations.RemoveField(
            model_name='governmentscheme',
            name='application_process_mr',
        ),
        migrations.RemoveField(
            model_name='governmentscheme',
            name='benefits_hi',
        ),
        migrations.RemoveField(
            model_name='governmentscheme',
            name='benefits_mr',
        ),
        migrations.RemoveField(
            model_name='governmentscheme',
            name='documents_required_hi',
        ),
        migrations.RemoveField(
            model_name='governmentscheme',
            name='documents_required_mr',
        ),
        migrations.RemoveField(
            model_name='governmentscheme',
            name='eligibility_hi',
        ),
        migrations.RemoveField(
            model_name='governmentscheme',
            name='eligibility_mr',
        ),
        migrations.RemoveField(
            model_name='governmentscheme',
            name='full_description_hi',
        ),
        migrations.RemoveField(
            model_name='governmentscheme',
            name='full_description_mr',
        ),
        migrations.RemoveField(
            model_name='governmentscheme',
            name='short_description_hi',
        ),
        migrations.RemoveField(
            model_name='governmentscheme',
            name='short_description_mr',
        ),
    ]
