# Generated by Django 6.1 on 2026-09-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('investment', models.CharField(max_length=100)),
                ('materials', models.TextField()),
                ('guide', models.TextField()),
            ],
        ),
    ]
