# Generated by Django 6.1 on 2026-09-03 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_skills', '0002_quizquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='women_skills.skill')),
            ],
            options={
                'ordering': ['stage_number'],
            },
        ),
    ]
