# Generated by Django 6.1 on 2026-09-04 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_skills', '0003_learningstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('investment', models.CharField(max_length=100)),
                ('time_required', models.CharField(max_length=100)),
                ('profit_potential', models.CharField(max_length=50)),
                ('where_to_sell', models.TextField()),
                ('related_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_ideas', to='women_skills.skill')),
            ],
        ),
    ]
