# Generated by Django 6.1 on 2026-09-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_skills', '0004_businessidea'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessidea',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
