# Generated by Django 6.1 on 2026-09-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_skills', '0005_businessidea_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_mr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='guide_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='guide_mr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_hi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_mr',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
