# Generated by Django 6.1 on 2026-09-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_skills', '0006_skill_description_hi_skill_description_mr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='materials_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='materials_mr',
            field=models.TextField(blank=True),
        ),
    ]
