# Generated by Django 6.1 on 2026-09-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_skills', '0007_skill_materials_hi_skill_materials_mr'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessidea',
            name='description_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessidea',
            name='description_mr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessidea',
            name='title_hi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='businessidea',
            name='title_mr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='businessidea',
            name='where_to_sell_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessidea',
            name='where_to_sell_mr',
            field=models.TextField(blank=True),
        ),
    ]
