# Generated by Django 6.1 on 2026-09-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_skills', '0008_businessidea_description_hi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='💰', max_length=10)),
                ('title_hi', models.CharField(blank=True, max_length=200)),
                ('description_hi', models.TextField(blank=True)),
                ('title_mr', models.CharField(blank=True, max_length=200)),
                ('description_mr', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellingTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🛍', max_length=10)),
                ('title_hi', models.CharField(blank=True, max_length=200)),
                ('description_hi', models.TextField(blank=True)),
                ('title_mr', models.CharField(blank=True, max_length=200)),
                ('description_mr', models.TextField(blank=True)),
            ],
        ),
    ]
