# Generated by Django 6.1 on 2026-09-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_skills', '0009_financialtip_sellingtip'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningstage',
            name='description_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningstage',
            name='description_mr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningstage',
            name='title_hi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='learningstage',
            name='title_mr',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
