# Generated by Django 6.1 on 2026-09-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_skills', '0010_learningstage_description_hi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='option_a_hi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_a_mr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_b_hi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_b_mr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_c_hi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_c_mr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_d_hi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_d_mr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_text_hi',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_text_mr',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
