# Generated by Django 6.1 on 2026-09-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_skills', '0011_quizquestion_option_a_hi_quizquestion_option_a_mr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtip',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sellingtip',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
