# Generated by Django 6.1 on 2026-09-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_skills', '0012_financialtip_image_url_sellingtip_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessidea',
            name='video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='financialtip',
            name='video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sellingtip',
            name='video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
