# Generated by Django 6.0.8 on 2026-08-29 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('kn', 'Kannada'), ('pa', 'Punjabi')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('season', models.CharField(blank=True, max_length=150)),
                ('soil', models.TextField(blank=True)),
                ('water_requirement', models.TextField(blank=True)),
                ('sowing_time', models.CharField(blank=True, max_length=200)),
                ('harvesting_time', models.CharField(blank=True, max_length=200)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='agriculture.crop')),
            ],
            options={
                'ordering': ['crop__name', 'language'],
                'constraints': [models.UniqueConstraint(fields=('crop', 'language'), name='unique_crop_language')],
            },
        ),
    ]
