# Generated by Django 6.0.8 on 2026-09-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0002_croptranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='common_problems',
            field=models.TextField(blank=True, help_text='Short common pests, diseases or problems.'),
        ),
        migrations.AddField(
            model_name='crop',
            name='farmer_tip',
            field=models.TextField(blank=True, help_text='One short practical tip for farmers.'),
        ),
        migrations.AddField(
            model_name='croptranslation',
            name='common_problems',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='croptranslation',
            name='farmer_tip',
            field=models.TextField(blank=True),
        ),
    ]
