# Generated by Django 6.0.1 on 2026-09-17 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('report_type', models.CharField(blank=True, max_length=100)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('extracted_information', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('report_image', models.FileField(blank=True, null=True, upload_to='health_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
