# Generated by Django 6.0.1 on 2026-09-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthreport',
            name='user',
        ),
    ]
