# Generated by Django 5.2.17 on 2026-10-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_remove_healthreport_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthreport',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
