# Generated by Django 6.1.1 on 2026-10-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_alter_healthreport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
