# Generated by Django 6.0.8 on 2026-08-27 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_class_subject_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lesson_number', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('youtube_video_id', models.CharField(max_length=50)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='education.chapter')),
            ],
            options={
                'ordering': ['lesson_number'],
            },
        ),
    ]
