# Generated by Django 6.0.8 on 2026-08-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='youtube_video_id',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_source',
            field=models.CharField(default='Wikimedia', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(default='https://example.com/video.mp4', max_length=500),
            preserve_default=False,
        ),
    ]
