# Generated by Django 6.0.8 on 2026-08-27 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_test_question_testresult_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='available_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='available_until',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
