# Generated by Django 6.0.8 on 2026-08-28 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_testattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='keyboard_violation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='last_proctoring_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='proctoring_status',
            field=models.CharField(choices=[('active', 'Active'), ('submitted', 'Submitted'), ('terminated', 'Terminated')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='termination_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='warning_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProctoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('camera_started', 'Camera Started'), ('camera_stopped', 'Camera Stopped'), ('phone_detected', 'Phone Detected'), ('laptop_detected', 'Laptop Detected'), ('book_detected', 'Book Detected'), ('multiple_persons', 'Multiple Persons'), ('copy_attempt', 'Copy Attempt'), ('paste_attempt', 'Paste Attempt'), ('cut_attempt', 'Cut Attempt'), ('tab_switch', 'Tab Switch'), ('focus_loss', 'Focus Loss'), ('fullscreen_exit', 'Fullscreen Exit'), ('keyboard_violation', 'Keyboard Violation'), ('warning', 'Warning'), ('test_terminated', 'Test Terminated')], max_length=50)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_events', to='education.testattempt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_proctoring_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
