# Generated by Django 6.0.8 on 2026-09-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_testattempt_keyboard_violation_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_source',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
