# Generated by Django 6.1.1 on 2026-09-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Education', 'Education'), ('Women & Child', 'Women & Child'), ('Employment', 'Employment'), ('Housing', 'Housing'), ('Health', 'Health'), ('Financial Assistance', 'Financial Assistance'), ('Social Welfare', 'Social Welfare')], max_length=100)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('benefits', models.TextField()),
                ('eligibility', models.TextField()),
                ('documents_required', models.TextField()),
                ('application_process', models.TextField()),
                ('implementing_department', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('official_url', models.URLField(blank=True)),
                ('helpline', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
